### ISSUE TITLE
provide / inject not found , overwrite by plugins.

### ISSUE THREAD

**Issue by TrungRueta** [vuejs/vue-function-api#66]
Hi team!

i am using vue-function-api as proxy to make project in Vue2 with Vue3 api style. Today i found issue with `provide` / `inject`:

first please see this code snippet :
[provide / inject failed jsfiddle demo](https://jsfiddle.net/trungrueta/e8zfsdnp/15/)

step:
1. run code, the preview box show white card html withthout any content.
2. in js box remove / comment the line : `Vue.use(VeeValidate, { inject: false })`.
3. run code, now inside white card show content injected.

Please see that in vee-validate plugin they allow disable auto-inject feature with option `inject: false`. But i dont know why `provide()` result replaced by other plugin, and dont know what `vee-validate` did underground.

other attention is: if use Vue2.x provide style :

```js
{
    provide: {
       T: { ok: true }
    }
}
```

then we can inject use `inject()` at any child component no issue!

**Comment by LinusBorg** [comment]
The issue is that this plugin adds a old-API `provide:` option as a global mixin to each component, and this "old-school" provide is resolved *after* `setup`'s provide and actually overrides what `setup has previously set `:

1. `setup` is run in Vue 2's `beforeCreate` hook
2. After that, Vue's "real" initialization of `provide:` options is done.
3. and that code overrides `this._provided` (as this is an internal that is not pre-set with any content, usually, when not using this function-api plugin).

The same problem can be demonstrated when doing this:
```
{
  setup() {
    provide('A', 'A')
  },
  provide: {
   B: 'B'
  }
}
```

The 'A' provide will be overwritten when Vue initializes the 'B' provide

**Comment by fessacchiotto** [comment]
@TrungRueta Hi! Have you had any success integrating vee-validate with the function api plugin? (For example, I found out that is possible to access the `fields`bag by referencing: `context.root.$validator._base.fields`, but I'd look for a better way...)

**Comment by TrungRueta** [comment]
@fessacchiotto yes, you can reference from this :
[vee-validate injector](https://baianat.github.io/vee-validate/concepts/injections.html#injecting-parent-validator)

if you init vee-validate plugin in vue `Vue.use(...)` then you will have `$validator` ready on every components, use `vue-function-api` -> `inject('...')` to pull it.

**Comment by fessacchiotto** [comment]
@TrungRueta Thank you! I still cannot access the validator property "fields" after the injection. I can only access it like this: `$validator.value._base.fields`. Otherwise it's always an empty array...
